FROM ghcr.io/graalvm/graalvm-community:21 AS builder
WORKDIR /workspace/app

COPY .mvn .mvn
COPY pom.xml mvnw ./
COPY src src

RUN ./mvnw clean -Pnative native:compile -DskipTests


FROM mcr.microsoft.com/azure-functions/base:4.0-slim AS runner

COPY --from=builder /workspace/app/target/database-native /app/

ENTRYPOINT ["./app/database-native"]
